name: Build and deploy demo
on:
  workflow_run:
    workflows:
      - Release
    types:
      - completed
jobs:
  deploy-demo:
    name: Build and deploy demo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: '16'
          cache: yarn
          cache-dependency-path: ./demo/yarn.lock
      - run: yarn install --frozen-lockfile
        working-directory: ./demo
      - run: yarn build
        working-directory: ./demo
      - uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847 # v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./demo/public/
          force_orphan: true
