name: Build and deploy demo
on:
  workflow_run:
    workflows:
      - Release
    types:
      - completed
jobs:
  deploy-demo:
    name: Build and deploy demo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d # v3.0.0
        with:
          version: latest
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version-file: .node-version
          cache: pnpm
          cache-dependency-path: ./demo/pnpm-lock.yaml
      - run: pnpm install
        working-directory: ./demo
      - run: pnpm build
        working-directory: ./demo
      - uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847 # v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./demo/public/
          force_orphan: true
