name: Build and deploy demo
on:
  workflow_run:
    workflows:
      - Release
    types:
      - completed
jobs:
  deploy-demo:
    name: Build and deploy demo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2
      - uses: actions/setup-node@eeb10cff27034e7acf239c5d29f62154018672fd # tag=v3.3.0
        with:
          node-version: '16'
          cache: yarn
          cache-dependency-path: ./demo/yarn.lock
      - run: yarn install --frozen-lockfile
        working-directory: ./demo
      - run: yarn build
        working-directory: ./demo
      - uses: peaceiris/actions-gh-pages@068dc23d9710f1ba62e86896f84735d869951305 # renovate: tag=v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./demo/public/
          force_orphan: true
