name: Build and deploy demo
on:
  workflow_run:
    workflows:
      - Release
    types:
      - completed
jobs:
  deploy-demo:
    name: Build and deploy demo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
        with:
          node-version: '16'
          cache: yarn
          cache-dependency-path: ./demo/yarn.lock
      - run: yarn install --frozen-lockfile
        working-directory: ./demo
      - run: yarn build
        working-directory: ./demo
      - uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847 # v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./demo/public/
          force_orphan: true
