name: Release
on:
  workflow_run:
    branches:
      - main
    workflows:
      - Test
    types:
      - completed
jobs:
  release:
    name: Release package
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # renovate: tag=v3.0.0
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
      - uses: actions/setup-node@5b52f097d36d4b0b2f94ed6de710023fbb8b2236 # tag=v3.1.0
        with:
          node-version: '16'
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
