name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2
      - uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93 # tag=v3.4.1
        with:
          node-version: '16'
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn test
  test-demo:
    name: Build demo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2
      - uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93 # tag=v3.4.1
        with:
          node-version: '16'
          cache: yarn
          cache-dependency-path: ./demo/yarn.lock
      - run: yarn install --frozen-lockfile
        working-directory: ./demo
      - run: yarn build
        working-directory: ./demo
